// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHpRJkTpTaY40MpRJMh-VlXzCOKDR7Ov0',
    appId: '1:465615538969:web:c38bcb24e6f48090079388',
    messagingSenderId: '465615538969',
    projectId: 'flashchat-75f78',
    authDomain: 'flashchat-75f78.firebaseapp.com',
    storageBucket: 'flashchat-75f78.appspot.com',
    measurementId: 'G-DJC0264Y0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaDAss0SKY-c4_0pQ-md9Tnc_ovgTnoeo',
    appId: '1:465615538969:android:f1cb232546acef11079388',
    messagingSenderId: '465615538969',
    projectId: 'flashchat-75f78',
    storageBucket: 'flashchat-75f78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALWCy3LtJ7OPRjmLyDl6NBKpW1mtmWTBA',
    appId: '1:465615538969:ios:e943408814b694a8079388',
    messagingSenderId: '465615538969',
    projectId: 'flashchat-75f78',
    storageBucket: 'flashchat-75f78.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALWCy3LtJ7OPRjmLyDl6NBKpW1mtmWTBA',
    appId: '1:465615538969:ios:e943408814b694a8079388',
    messagingSenderId: '465615538969',
    projectId: 'flashchat-75f78',
    storageBucket: 'flashchat-75f78.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHpRJkTpTaY40MpRJMh-VlXzCOKDR7Ov0',
    appId: '1:465615538969:web:2850b97dd6b8edfe079388',
    messagingSenderId: '465615538969',
    projectId: 'flashchat-75f78',
    authDomain: 'flashchat-75f78.firebaseapp.com',
    storageBucket: 'flashchat-75f78.appspot.com',
    measurementId: 'G-9FKM0WY45F',
  );

}